name: Build APK
on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python_version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libffi-dev python3-dev libssl-dev zlib1g-dev \
          libncurses5-dev libncursesw5-dev libreadline-dev libsqlite3-dev tk-dev libgdbm-dev \
          libc6-dev libbz2-dev libffi-dev autoconf libtool pkg-config cmake ant \
          openjdk-17-jdk unzip zip

      - name: Install Buildozer & Cython
        run: |
          pip install --user "Cython==0.29.33" virtualenv buildozer
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build Android APK (The Bash Script Method)
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          
          # ہم ایک الگ اسکرپٹ بنا رہے ہیں تاکہ گٹ ہب کا 'Broken pipe' ایرر اسے روک نہ سکے
          cat << 'EOF' > build_script.sh
          #!/bin/bash
          yes y | buildozer android debug
          EOF
          
          chmod +x build_script.sh
          ./build_script.sh

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: HTML-to-APK-App
          path: bin/*.apk
